Python/KadanesAlgorithm.py

- Add Python Programs #2
- Added Kadanes Algorithm

Added Kadanes Algorithm #2

---

Python/TextWrap.py
Python/hashing.py

python program for hashing and Text wrapping added

New Program files added

---

Python/DPknapsack.py

0/1 Knapsack using Dynamic Programming.
Issue : 2

0/1 Knapsack using Dynamic Programming added.

---

Python/Python_Program_for_Extended_Euclidean_algorithms.py

I love the Extended Euclidean Algorithm

Python Program for Extended Euclidean Algorithm

---

Python/kosaraju_algorithm.py

================== KOSARAJU'S ALGORYTHM ================== 
1) Create an empty stack 'S', do DFS on a graph, on the road, insert the vertices on top of this stack.
2) Obtain the Transpose Graph, just reverse the graph
3) One by one pop each vertex from S while S is not empty. 
4) Let popped vertex be 'v', so it will be the source, do DFS on it. The DFS starting from 'v' 
will denote the strongly connected components (SCC) of 'v', one by one popped from stack.

Adding Kosaraju's algorithm written in Python, CLOSES #22

---

Python/reverseArray.py

Python program for reversal algorithm of array rotation

reverseArray.py

---

Python/stackimplementation.py

Added the basic Stack implementation algorithm in python programming language.

Stack implementation in python

---

Python/Sorting/Bubblesort.py
Python/Sorting/CountingSort.py
Python/Sorting/HeapSort.py
Python/Sorting/InsertionSort.py
Python/Sorting/MergeSort.py
Python/Sorting/QuickSort.py
Python/Sorting/SelectionSort.py

Included sorting algorithms like:
1. Bubble Sort
2. Selection Sort
3. Insertion Sort
4. Counting Sort
5. Merge Sort
6. Heap Sort
7. Quick Sort

Created folder for Sorting under Python directory.

---

Python/isAnagram.py
Python/knn.py

- Add Python Programs #2
- Implemented K Nearest Neighbor Algorithm in Python.

Added K Nearest Neighbor Algorithm #2

---

Python/check_if_a_string_is_palindrome_or_not.py

Check if string is palindrome or not

---

Python/OptimizedFibonacci.py

Optimized code for calculating a fibonacci number at a particular position

Added fibonacci calculation using direct formula

---

Python/Squares of Sorted Array.py

- Add Python Programs #2
- Added Squares of a Sorted Array.

Added Squares of Sorted Array #2

---

Java/Fibonacci.java

Thank you for the opportunity.
More PRs are coming.

Added Fibonacci Sequence Generator

---

Python/binary search algorithm

THIS CODE WILL HELP YOU TO SEARCH A SPECIFIC WORD FROM A ENTERED LIST

BINARY SEARCH ALGORITHM

---

Python/Median of Two Sorted Arrays.py

Added Median Sorted Arrays Problem in Python

Added Median Sorted Arrays in Python

---

CPP/BinaryIndexedTree(Fenwick Tree).cpp

Binary Indexed Tree (Fenwick Tree)

Binary Indexed Tree (Fenwick Tree)

---

Python/stack_permutation.py

Hey, I have added a new Python Algorithm to Check Stack Permutations. Please merge this commit.
Thank you.

Adding Check Stack Permutation Algorithm in Python

---

C++/Binet_fibonacci.cpp

Added a rare algorithm to find nth term of a fibonacci with proper explanation

Added Binet's Formula to find the nth term of a Fibonacci

---

C++/Dijkstra.cpp

Implemented Dijsktra's Algorithm for a Weighted Graph using Priority Queue

Added Dijkstra's Algorithm for a Weighted Graph

---

Finding the Eulerian path

Finding the Eulerian path  in O(M)

Finding the Eulerian path

---

Strong Orientation of undirected graph

Strong Orientation of undirected graph(connected graphs are exactly the graphs that have strong orientations is called Robbins' theorem.

Strong Orientation of undirected graph

---

Finding Bridges Online

Finding Bridges Online with O(N+M)

Finding Bridges Online

---

Paint the edges of the tree

Paint the edges of the tree Used in CP algorithm

Paint the edges of the tree

---

C++/TwoPointer'sAlgorithm.cpp

this file has the code of two pointers algorithm, which is majorly used in multiple coding questions.
@Defcon27 please add the label hacktoberfest-accepted

solution to two pointers algorithm
